# fly.toml app configuration file generated for fly-minio on 2024-11-29T17:56:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-minio'
primary_region = 'fra'

[build]
  image = "minio/minio"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "miniodata"
  destination = "/data"

[services]
  [[services.ports]]
    handlers = ["http"]
    port = "9000"
    internal_port = "9000"

  [[services.ports]]
    handlers = ["http"]
    port = "9001"
    internal_port = "9001"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 0